# Generated by Django 2.1 on 2018-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY', models.CharField(blank=True, max_length=255, null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('CUSTOM_FLD_IDS', models.TextField(null=True)),
                ('CUSTOM_FLD_DATA', models.TextField(null=True)),
                ('STAGE_CODE', models.IntegerField(null=True)),
                ('STAGE_DESC', models.CharField(blank=True, max_length=255, null=True)),
                ('USER_CODE', models.IntegerField(null=True)),
                ('NOTES', models.TextField(null=True)),
                ('PW_LINK', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
