# Generated by Django 2.1 on 2018-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180804_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='STAGE_CODE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
