# Generated by Django 2.1 on 2018-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180804_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='TIME_SPEND',
            field=models.IntegerField(null=True),
        ),
    ]
