# Generated by Django 2.1 on 2018-08-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_time_spend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_TIME', models.DateTimeField(blank=True, null=True)),
                ('END_TIME', models.DateTimeField(blank=True, null=True)),
                ('STAGE_CODE', models.CharField(blank=True, max_length=255, null=True)),
                ('STAGE_DESC', models.CharField(blank=True, max_length=255, null=True)),
                ('TIME_SPEND', models.IntegerField(null=True)),
                ('COMPANY_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='company.Company')),
            ],
            options={
                'db_table': 'company_stages',
            },
        ),
    ]
