# Generated by Django 2.1 on 2018-08-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companystages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystages',
            name='COMPANY_ID',
        ),
    ]
