# Generated by Django 2.1 on 2018-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_companystages_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystages',
            name='COMPANY_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
